name: manager
description: Create a new hashed password for the server
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  dbcrypt: ^2.0.0
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
